//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVIBES
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string type { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Qtu { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Tb_Hotels Tb_Hotels { get; set; }
    }
}
