//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVIBES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfInvoice { get; set; }
        public Nullable<int> ConferencesID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> vatcustom { get; set; }
        public Nullable<bool> ISPaid { get; set; }
        public Nullable<decimal> TaxCusto { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> ISCancel { get; set; }
        public Nullable<bool> ISprinted { get; set; }
        public Nullable<bool> userID { get; set; }
    
        public virtual Tb_Conferences Tb_Conferences { get; set; }
        public virtual Tb_suppliers Tb_suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
