//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVIBES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VibesDataSourceEntities : DbContext
    {
        public VibesDataSourceEntities()
            : base("name=VibesDataSourceEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Login> Tb_Login { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tb_Categories> Tb_Categories { get; set; }
        public virtual DbSet<Tb_Conferences> Tb_Conferences { get; set; }
        public virtual DbSet<Tb_Customers> Tb_Customers { get; set; }
        public virtual DbSet<Tb_expences> Tb_expences { get; set; }
        public virtual DbSet<Tb_Hotels> Tb_Hotels { get; set; }
        public virtual DbSet<Tb_Revinues> Tb_Revinues { get; set; }
        public virtual DbSet<Tb_suppliers> Tb_suppliers { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
    
        public virtual int sp_login(string user, ObjectParameter fullName, string password, ObjectParameter typeOfUser)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_login", userParameter, fullName, passwordParameter, typeOfUser);
        }
    }
}
