//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVIBES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Customers()
        {
            this.Tb_Conferences = new HashSet<Tb_Conferences>();
        }
    
        public int ID { get; set; }
        public string TypeofCustomer { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string Note { get; set; }
        public string CustomerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Conferences> Tb_Conferences { get; set; }
    }
}
