//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVIBES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Login
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Logpassword { get; set; }
        public string FullName { get; set; }
        public string TypeOfUser { get; set; }
    }
}
